<? captureStart('headerLogoutLink'); ?><?= URIGenerator::tag("LOGOUT") ?> <? $headerLogoutLink = captureEnd('headerLogoutLink'); ?>
<? captureStart('headerSearchLink'); ?><?= URIGenerator::tag("SEARCH") ?> <? $headerSearchLink = captureEnd('headerSearchLink'); ?>
<? captureStart('headerStoreLink'); ?><?= URIGenerator::tag("PARTS_STORE") ?> <? $headerStoreLink = captureEnd('headerStoreLink'); ?>
<? captureStart('headerRepairLink'); ?><?= URIGenerator::tag("GUIDE") ?> <? $headerRepairLink = captureEnd('headerRepairLink'); ?>
