<li><a rel="Answers" <? if (!(ServerConstants::enabled('feature-answers-is-discussion') && $question->is_discussion) && !$showDeleted): ?>class="active"<? endif; ?>>
<li><a rel="Oldest" <? if (ServerConstants::enabled('feature-answers-is-discussion') && $question->is_discussion && !$showDeleted): ?>class="active"<? endif; ?>>

<? if ($question->status != 'closed'): ?><? endif; ?>

<? if ((!$isLoggedIn || $events->allowed()) && $question->status != 'closed'): ?>
   <? $canAnswer = true; ?>
<? else: ?>
   <? $canAnswer = false; ?>
<? endif; ?>

<? if (check($modVoteAllowed, false) && ($curUserid != $post->userid || check($canForceVote, false))): ?><? endif; ?>
<? if ($aConf->search !== false): ?> for <em><?= wordbreak($aConf->search, 20) ?></em><? endif; ?>
<? if ($question->userid === $curUserid && (!$post->isQuestion) && !($question->is_discussion)): ?>
   &bull;
   <a id="acceptAnswer-<?= $post->postid ?>" class="muted toggleAcceptLink" 
   data-postid="<?= $post->postid ?>">
    <? if ($accepted): ?><?= ___("Unaccept Answer") ?><? else: ?><?= ___("Accept Answer") ?><? endif; ?></a>
<? elseif ($search): ?>
   <?= ___("Hello world") ?>
<? endif; ?>

 <? if ($question->blurb->is_discussion): ?><? endif; ?>

