<?= $Name ?>
<?= $product['part_no'] ?> <b><?= $product['description'] ?></b>
<?= $Contacts["row"]['Phone'] ?>

Hello <?= $firstname ?> <?= $lastname ?>, glad to see you can make it.
<br />
<? /*  this will not work as $variables are case sensitive  */ ?>
This weeks meeting is in <?= $meetingplace ?>.
<? /*  this will work  */ ?>
This weeks meeting is in <?= $meetingPlace ?>.

<?= $Contacts['fax'] ?><br />
<?= $Contacts['email'] ?><br />
<? /*  you can print arrays of arrays as well  */ ?>
<?= $Contacts['phone']['home'] ?><br />
<?= $Contacts['phone']['cell'] ?><br />
<?= $Contacts['phone']->cell() ?>

<?= check($Contacts['phone']['cell']['iphone'], false) ?><br />
<?= escape($Contacts['phone']['cell']['iphone'], 'html') ?><br />

<?= $post->blurbs['questions["0"]'] ?>

<input type="text" name="search" value="<?= escape($aConf->search) ?>" />
