#! /bin/bash

PYTHON=python3

#if [ $2 -eq 1 ] ; then 
#   python26 main.py -d $1
#else 
testdir='./test/'
phtml='.phtml'
tpl='.tpl'
filename=$1
input=$testdir$filename$tpl
output=$filename$phtml

$PYTHON main.py -s $input -p $output
#fi
